# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 517f82751342ee6b49dc1aa59105fcfb79c5ac2f29268bc5c3fb0dc3111122aebba8d49f507f745ca91f420561542e416e3a3d1d36211d08e5340c9f1f9e7037

test:
  secret_key_base: a274888ff32449911f0595913173c58489442cc91e0ce3d6e6c4b6095c16a5a9a8a7ef6e78a90e5b0815a0fad26cd48d65e61f3ad66ffb6c04c3bfec51bf1cc3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
